name: Example

on: [push, pull_request]

env:
  GOTOOLCHAIN: local

jobs:
  go122:
    name: go1.22
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - run: go version
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
      - run: golangci-lint --version

      - run: golangci-lint run

  go123:
    name: go1.23
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - run: go version
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
        env:
          GOTOOLCHAIN: go1.22.1
      - run: golangci-lint --version

      - run: golangci-lint run
